apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: portal-api
profiles:
  - name: local
    build:
      googleCloudBuild:
        projectId: cwb07-shared-services-7b30
        gradleImage: gradle:8.2.1-jdk17-alpine
      artifacts:
        - image: us-west1-docker.pkg.dev/cwb07-shared-services-7b30/application/cwb07-portal-api
          jib:
            type: gradle
            project: service
            args:
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=cloud"
    deploy:
      helm:
        releases:
          - name: cwb07-portal-api
            createNamespace: true
            chartPath: helm/portal-api
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_portal_api}}"
              image.tag: "{{.IMAGE_TAG_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_portal_api}}@{{.IMAGE_DIGEST_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_portal_api}}"
            setValues:
              environment: local
            valuesFiles:
              - helm/portal-api/values.yaml
              - helm/portal-api/local.yaml
  - name: minikube
    activation:
      - kubeContext: minikube
    build:
      artifacts:
        - image: portal-api
          jib:
            type: gradle
            project: service
            args:
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=local"
    manifests:
      helm:
        releases:
          - name: portal-api
            createNamespace: true
            chartPath: helm/portal-api
            valuesFiles:
              - helm/portal-api/values.yaml
              - helm/portal-api/local.yaml
            setValues:
              environment: local
              net.readinessProbe.initialDelaySeconds: 60
              pullPolicy: IfNotPresent
              postgres.enabled: "true"
            setValueTemplates:
              image.repository: portal-api
              image.tag: portal-api
    deploy:
      statusCheckDeadlineSeconds: 60
      tolerateFailuresUntilDeadline: true
      helm: {}
    portForward:
      - resourceType: service
        resourceName: portal-api
        namespace: cwb07
        port: 80
        localPort: 8080
      - resourceType: service
        resourceName: portal-api-postgres
        namespace: cwb07
        port: 5432
        localPort: 5438
  - name: dev
    build:
      googleCloudBuild:
        projectId: cwb07-shared-services-7b30
        gradleImage: gradle:8.2.1-jdk17-alpine
      artifacts:
        - image: us-west1-docker.pkg.dev/cwb07-shared-services-7b30/application/cwb07-portal-api
          jib:
            type: gradle
            project: service
            args:
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=cloud"
    deploy:
      helm:
        releases:
          - name: cwb07-portal-api
            createNamespace: true
            chartPath: helm/portal-api
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_portal_api}}"
              image.tag: "{{.IMAGE_TAG_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_portal_api}}@{{.IMAGE_DIGEST_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_portal_api}}"
            setValues:
              environment: dev
            valuesFiles:
              - helm/portal-api/values.yaml
              - helm/portal-api/dev.yaml
  - name: prod
    build:
      googleCloudBuild:
        projectId: cwb07-shared-services-7b30
        gradleImage: gradle:8.2.1-jdk17-alpine
      artifacts:
        - image: us-west1-docker.pkg.dev/cwb07-shared-services-7b30/application/cwb07-portal-api
          jib:
            type: gradle
            project: service
            args:
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=cloud"
    deploy:
      helm:
        releases:
          - name: cwb07-portal-api
            createNamespace: true
            chartPath: helm/portal-api
            # Ref: https://skaffold.dev/docs/deployers/helm/#image-configuration
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_portal_api}}"
              image.tag: "{{.IMAGE_TAG_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_portal_api}}@{{.IMAGE_DIGEST_us_west1_docker_pkg_dev_cwb07_shared_services_7b30_application_cwb07_portal_api}}"
            setValues:
              environment: prod
            valuesFiles:
              - helm/portal-api/values.yaml
              - helm/portal-api/prod.yaml
