apiVersion: v2
name: portal-api
description: Helm Chart for the Portal API
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: postgres
    version: 0.0.1
    condition: postgres.enabled