environment: "local"
createIngress: true
isGke: false

postgres:
  enabled: false
  namespace: "cwb07"
  persistence:
    size: 1Gi
  env:
    POSTGRES_DB: "local-portal-api-db"
    POSTGRES_HOST: 'postgres-14-alpine'
    POSTGRES_PASSWORD: "root"
    POSTGRES_PORT: 5432
    POSTGRES_USER: "root"

net:
  host: "api.cwb07.test"

env:
  ALLOWED_ORIGINS: "http://localhost:4200, http://localhost:4201, http://agency.cwb07.test, http://public.cwb07.test, http://employer.cwb07.test"
  CERBOS_URI: "127.0.0.1:3592"
  DB_CONNECTION_URL: "jdbc:postgresql://portal-api-postgres:5432/local-portal-api-db"
  DB_USERNAME: "root"
  DB_PASSWORD: "root"
  GCP_PROJECT_ID: "cwb07-dev-ac55"
  OTEL_SAMPLER_PROBABILITY: 1.0 # valid values: [0.0 - 1.0]
  PUBSUB_EMULATOR_HOST: "pubsub-emulator-service:8085" # set actual "host:port" to enable or false to disable
  PUBSUB_EMULATOR_ENABLED: true # set to true to enable emulator
  # topics separated by comma
  PUBSUB_SUBSCRIPTIONS: "projects/cwb07-dev-ac55/subscriptions/APPLICATION_ROLE_CAPABILITIES_SUBSCRIPTION"
  SUBSCRIBER_TOPICS: "APPLICATION_ROLE_REPORTING"
