name: File Change Notification

on:
  push:
    paths:
      - 'skaffold.yaml'
      - 'helm/portal-api/values.demo.yaml'
      - 'helm/portal-api/values.dev.yaml'
      - 'helm/portal-api/values.local.yaml'
    branches:    
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Notify on File Change
      run: python .github/scripts/notify_on_file_change.py
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.DSGOV_SLACK_WEBHOOK }}
